### ISSUE TITLE
try catch inside codon

### ISSUE THREAD

**Issue by Tusenka** [exaloop/codon#760]
**Given:**
```
      try:
            raise Exception("some exception")
       except Exception as e:
            logger.exception(
                "Невозможно завершить транзакцию. Откат изменений... %s",
                e
            )
```
**Error:**
`'Exception' object has no attribute '__to_py__'`

**Comment by ghuls** [comment]
Seems to work with Codon 0.19.6 (at least with 0.19.4 it didn't print anything):
```python
$ cat try_catch.codon
try:
    raise Exception("some exception")
except Exception as e:
    print(e)

# Codon v0.19.6
$ codon run try_catch.codon
some exception
```
