### ISSUE TITLE
strange issue with int

### ISSUE THREAD

**Issue by gcasale82** [exaloop/codon#384]
Testing this script with codon : 
=====
#normal python benchmark
from time import time
start = time()
datafile = open("ldata.csv" , "r")
d = datafile.read().split("\n")
Xs = d[0]
Ys = d[1]
datafile.close()
X = [int(x) for x in Xs.split(",") ]
Y = [int(y) for y in Ys.split(",") ]
#z = x + y^2 + 2
def formula(x:int , y:int ):
    return x + y**2 + 2
E = tuple(zip(X,Y))
Z = [formula(x,y) for x,y in E]
total = sum(Z[:100])
end = time()
total_time = end - start
print(f"Total is {total} and execution time is {total_time} seconds ")
======
works in python3.11 but not in codon :
`
casale@deb-hp-8300:~/benchmark$ python311 test2.py 
Total is 328416 and execution time is 0.0006239414215087891 seconds 
gcasale@deb-hp-8300:~/benchmark$ codon run -release test2.py
test2.py:18:5-32: error: 'int' object has no attribute '__getitem__'
`

**Comment by arshajii** [comment]
Hi @gcasale82 -- the issue is `E = tuple(zip(X,Y))`, which won't work in Codon since tuple lengths need to be known at compile time. You can just change this to a list though: `E = list(zip(X,Y))`.

@inumanag it seems we allow e.g. `tuple(zip([1,2,3], [4,5,6]))` to pass the type checker, and it just gives an empty tuple -- we should probably check this...

**Comment by gcasale82** [comment]
Hi , thanks for replying , it worked , loading a 555MB csv  , trasforming to lists and performing some computation , performance are similar to GO , very good results , considering that with python the program was few lines of code :
`gcasale@deb-hp-8300:~/benchmark/high$ ls -lh data.csv
-rw-r--r-- 1 gcasale gcasale 555M 18 mag 16.24 data.csv`
`gcasale@deb-hp-8300:~/benchmark/high$ go run go_bench.go 
Sum of the first 100 elements of Z: 293790
Total time spent: 11.093617701`
`gcasale@deb-hp-8300:~/benchmark/high$ codon run -release bench_cod.py 
Total is 293790 and execution time is 13.3105 seconds 
gcasale@deb-hp-8300:~/benchmark/high$ cat bench_cod.py `
`gcasale@deb-hp-8300:~/benchmark/high$ wc -l go_bench.go 
72 go_bench.go`
`gcasale@deb-hp-8300:~/benchmark/high$ wc -l bench_cod.py 
19 bench_cod.py`

Python code is :
#normal python benchmark
from time import time
start = time()
datafile = open("data.csv" , "r")
d = datafile.read().split("\n")
Xs = d[0]
Ys = d[1]
datafile.close()
X = [int(x) for x in Xs.split(",") ]
Y = [int(y) for y in Ys.split(",") ]
#z = x + y^2 + 2
def formula(x:int , y:int ):
    return x + y**2 + 2
Z = [formula(x,y) for x,y in zip(X,Y)]
total = sum(Z[:100])
end = time()
total_time = end - start
print(f"Total is {total} and execution time is {total_time} seconds ")

**Comment by gcasale82** [comment]
closed since resolved
